<?php

return [
    // Header & Labels
    'title' => 'Capital / Shareholders',
    'subtitle' => 'Manage shareholders and capital allocation',
    'add_new' => 'Add New Capital',
    
    // Table Columns
    'owner' => 'Owner Name',
    'share_percent' => 'Share %',
    'amount' => 'Amount',
    'currency' => 'Currency',
    'price_usd' => 'Price (USD)',
    'balance_usd' => 'Balance (USD)',
    'created_by' => 'Created By',
    'date' => 'Date',
    'action' => 'Actions',

    // Messages
    'saved_success' => 'Capital saved successfully',
    'limit_reached' => 'Limit Reached: Total shares cannot exceed 100%!',
    'total_share_error' => 'Error: Total shares cannot exceed 100%',
    'share_limit_error' => 'Error: Total shares cannot exceed 100%. Current: :current%, Adding: :adding%.',

    // Trash & Alerts
    'trash' => 'Trash',
    'trash_empty' => 'Trash is empty',
    'back' => 'Back to List',
    'deleted_by' => 'Deleted By',
    'deleted_at' => 'Deleted At',
    'restore' => 'Restore',
    'perm_delete' => 'Delete Forever',
    
    // Bulk Actions
    'selected' => 'items selected',
    'restore_selected' => 'Restore Selected',
    'delete_selected' => 'Delete Selected',
    'cancel' => 'Cancel',

    // SweetAlert Messages
    'warning_perm_delete' => 'Are you sure?',
    'cant_undone' => 'This action cannot be undone!',
    'yes_delete' => 'Yes, delete it!',
    
    // PDF Report
    'report_title' => 'Capital & Shareholder Report',
    'exchange_rate' => 'Exchange Rate',
    'totals' => 'TOTALS',
    'generated_by' => 'Generated by System',
      'cancel' => 'Cancel',
    'reset-layout'=>'reset lay out',
    'Columns'=>'columns'
];