<?php

namespace App\Http\Controllers;

use App\Models\GroupSpending;
use App\Models\Branch;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class GroupSpendingController extends Controller
{
    public function index()
    {
        // Show ONLY active items in the main sheet
        $groups = GroupSpending::with(['branch', 'creator'])->latest()->get();
        $branches = Branch::where('is_active', true)->get();
        
        return view('spending.groups.index', compact('groups', 'branches'));
    }

    // NEW: Show only deleted items
    public function trash()
    {
        $groups = GroupSpending::onlyTrashed()->with(['branch', 'creator'])->latest()->get();
        return view('spending.groups.trash', compact('groups'));
    }

  public function store(Request $request)
{
    $data = $request->validate([
        'spendings' => 'required|array',
        'spendings.*.name' => 'required|string|max:255',
        'spendings.*.code' => 'nullable|string|max:255', // <--- CHANGED to nullable
        'spendings.*.accountant_code' => 'nullable|string',
        'spendings.*.branch_id' => 'required|exists:branches,id',
        'spendings.*.id' => 'nullable|exists:group_spendings,id',
    ]);

    DB::transaction(function () use ($data) {
        foreach ($data['spendings'] as $row) {
            if (isset($row['id']) && $row['id']) {
                // Update Existing (Don't update code, keep it as is)
                GroupSpending::where('id', $row['id'])->update([
                    'name' => $row['name'],
                    // 'code' => $row['code'], // Remove this line to prevent changing code on update
                    'accountant_code' => $row['accountant_code'],
                    'branch_id' => $row['branch_id'],
                ]);
            } else {
                // Create New (Code is handled by Model boot)
                GroupSpending::create([
                    'name' => $row['name'],
                    // Code is auto-generated by model
                    'accountant_code' => $row['accountant_code'],
                    'branch_id' => $row['branch_id'],
                    'created_by' => auth()->id(),
                ]);
            }
        }
    });

    return back()->with('success', __('spending.updated'));
}
    public function destroy($id)
    {
        GroupSpending::findOrFail($id)->delete();
        return back()->with('success', __('spending.deleted'));
    }

    public function restore($id)
    {
        GroupSpending::withTrashed()->findOrFail($id)->restore();
        return back()->with('success', 'Restored successfully.');
    }

    // NEW: Permanently Delete
    public function forceDelete($id)
    {
        GroupSpending::withTrashed()->findOrFail($id)->forceDelete();
        return back()->with('success', 'Permanently deleted.');
    }
}